version: '3.7'
services:
    nginx-web:
        image: nginx:latest
        #Restart container always when run service
        restart: always
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./public:/var/www/html/public
        links:
            - php-code
    php-code:
        # depends_on:
        #     - db
        build:
            context: .
            dockerfile: Dockerfile
        # image: digitalocean.com/php
        #Get the newest version of PHP
        image: php:7.4-fpm
        tty: true
#        environment:
#            SERVICE_NAME: app
#            SERVICE_TAGS: dev
        # working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html
            - ./storage/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - db
    db:
        image: mysql:latest
        # container_name: db
        # command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=testdb
            # - MYSQL_USER=root
            # - MYSQL_PASSWORD=12345
            # - MYSQL_TCP_PORT=3306
            # - MYSQL_DEFAULT_AUTH=mysql_native_password
        volumes:
            - ./database:/var/lib/mysql
            # - ./docker-init-queries.sql:/docker-entrypoint-initdb.d/init.sql
    php-myadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - PMA_HOST=db
            # - PMA_USER=root
            # - PMA_PASSWORD=password
        depends_on:
            - db
        # links:
        #     - db
