version: '3'
services:
    nginx-web:
        image: nginx:latest
        #Restart container always when run service
        restart: always
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./code:/code
        links:
            - php-code
    php-code:
        build:
#            context: .
            dockerfile: Dockerfile
#        image: digitalocean.com/php
        #Get the newest version of PHP
        image: php:7.3-fpm
#        tty: true
#        environment:
#            SERVICE_NAME: app
#            SERVICE_TAGS: dev
#        working_dir: /code
        volumes:
            - ./code:/code
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - db
    db:
        image: mysql:latest
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=testdb
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - ./dbdata:/var/lib/mysql
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - PMA_HOST=db
